<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="MyGameCollection.Default" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>


<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam adipiscing imperdiet augue, sit amet commodo magna faucibus eget. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer molestie, mi sit amet dapibus convallis, arcu nulla mollis dui, vitae tristique nisi augue quis augue. Morbi quis ultricies lectus. Praesent nec pharetra massa. Aliquam varius enim eget sapien blandit pretium. Aliquam tempor, ligula in facilisis egestas, velit urna interdum eros, a malesuada odio diam ac libero. Sed placerat, urna eu vulputate facilisis, libero dui porta ante, ut dignissim neque turpis auctor diam. Nullam convallis lacus ac aliquet rhoncus. Ut accumsan auctor mauris nec semper. Maecenas fermentum rhoncus porttitor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse magna eros, sollicitudin at dapibus vitae, dapibus non ligula. Curabitur sed eleifend elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque erat justo, consectetur eget est vitae, fringilla tempor elit.
    </p>
    <p>Nulla vestibulum commodo elit, et bibendum mi auctor sit amet. Cras sit amet enim facilisis, dignissim ligula nec, sagittis turpis. Morbi ut purus et elit dignissim imperdiet. Sed auctor quam quis odio tincidunt placerat. Donec auctor justo diam, lacinia tincidunt turpis dictum vitae. Praesent quis augue suscipit, volutpat purus ut, mattis justo. Praesent id blandit enim, in dictum turpis. Nulla convallis commodo porttitor. Maecenas vel sem neque. Integer et pharetra velit. Sed lobortis purus enim, at venenatis elit mollis nec. Maecenas rutrum dapibus lorem, nec lacinia lectus tristique et. Aliquam sit amet porta augue.</p>
</asp:Content>
